language: php

addons:
  code_climate:
    repo_token: 27ac36f4152db6ff30566b24803eb84b4cba86999be79288f9d414a5c5efb46a

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update --preview
  - travis_retry composer install --prefer-dist --no-interaction --dev

script:
  - bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/test-reporter
